#!/bin/bash

# This script detects if the widget is already installed.
# If it is, it will use --upgrade instead and restart plasmashell.

packageNamespace=`kreadconfig5 --file="$PWD/package/metadata.desktop" --group="Desktop Entry" --key="X-KDE-PluginInfo-Name"`
packageServiceType=`kreadconfig5 --file="$PWD/package/metadata.desktop" --group="Desktop Entry" --key="X-KDE-ServiceTypes"`
restartPlasmashell=false

for arg in "$@"; do
	case "$arg" in
		-r) restartPlasmashell=true;;
		--restart) restartPlasmashell=true;;
		*) ;;
	esac
done

isAlreadyInstalled=false
kpackagetool5 --type="${packageServiceType}" --show="$packageNamespace" &> /dev/null
if [ $? == 0 ]; then
	isAlreadyInstalled=true
fi

if $isAlreadyInstalled; then
	# Eg: kpackagetool5 -t "Plasma/Applet" -u package
	kpackagetool5 -t "${packageServiceType}" -u package
	restartPlasmashell=true
else
	# Eg: kpackagetool5 -t "Plasma/Applet" -i package
	kpackagetool5 -t "${packageServiceType}" -i package
fi

if $restartPlasmashell; then
	if which systemctl >/dev/null && systemctl is-active -q --user plasma-plasmashell.service; then
		systemctl restart --user plasma-plasmashell.service
	else
		killall plasmashell
		kstart5 plasmashell
	fi
fi

# install our version of Variety set_wallpaper that knows to talk to our plugin
[ -e $HOME/.config/variety/scripts/set_wallpaper ] && cp "$PWD/variety_set_wallpaper" $HOME/.config/variety/scripts/set_wallpaper
